# Generated by Django 5.0.3 on 2024-03-09 14:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0007_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_img'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='photos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_img'),
        ),
    ]
