# Generated by Django 5.0.3 on 2024-03-11 16:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0008_alter_product_image_alter_productimage_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image'),
        ),
    ]
