# Generated by Django 5.0.3 on 2024-03-11 17:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0010_alter_product_image_alter_productimage_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='photos',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='product_images'),
        ),
    ]
